### ISSUE TITLE
Question about OUTPUT

### ISSUE THREAD

**Issue by HaiDang2001VN** [HKUST-Aerial-Robotics/Pinhole-Fisheye-Mapping#2]
@WANG-KX thank you and your team for great works of solving this problem. But I have some issue with running it on my GeForce 840M (-arch=50) Laptop.
______________________________________________________________________________________________________________
Could you please provide some further details for output of pinhole_mapping?
I have tried and sucessfully run it on my 16.04 (GCC 5.4.0 with CUDA 8.0).

But after search through catkin_ws, I don't see any folder called ```col_depth```. I'm pretty sure that compilation is correct as just some warnings (about non-reachable codes and others of opencv) occurred:
```bash
[ 33%] Building CXX object pinhole_mapping/CMakeFiles/pinhole_mapping.dir/src/depthmap.cpp.o
/home/buiminh/Workspace/Mapper/catkin_ws/src/pinhole_mapping/src/seed_matrix.cu(115): warning: dynamic initialization in unreachable code

/home/buiminh/Workspace/opencv/modules/flann/include/opencv2/flann/lsh_table.h(220): warning: statement is unreachable

/home/buiminh/Workspace/opencv/modules/flann/include/opencv2/flann/lsh_table.h(225): warning: statement is unreachable

/home/buiminh/Workspace/opencv/modules/flann/include/opencv2/flann/lsh_table.h(234): warning: statement is unreachable

/home/buiminh/Workspace/opencv/modules/flann/include/opencv2/flann/index_testing.h(248): warning: variable "p1" was set but never used

/home/buiminh/Workspace/Mapper/catkin_ws/src/pinhole_mapping/src/seed_matrix.cu(115): warning: dynamic initialization in unreachable code

[ 44%] Linking CXX shared library /home/buiminh/Workspace/Mapper/catkin_ws/devel/lib/libpinhole_mapping.so
[ 44%] Built target pinhole_mapping
[ 55%] Linking CXX shared library /home/buiminh/Workspace/Mapper/catkin_ws/devel/lib/libpinhole_mapping_cuda.so
[ 55%] Built target pinhole_mapping_cuda
[ 66%] Building CXX object pinhole_mapping/CMakeFiles/pinhole_mapping_node.dir/src/publisher.cpp.o
[ 77%] Building CXX object pinhole_mapping/CMakeFiles/pinhole_mapping_node.dir/src/depthmap_node.cpp.o
[ 88%] Building CXX object pinhole_mapping/CMakeFiles/pinhole_mapping_node.dir/src/main_ros.cpp.o
[100%] Linking CXX executable /home/buiminh/Workspace/Mapper/catkin_ws/devel/lib/pinhole_mapping/pinhole_mapping_node
[100%] Built target pinhole_mapping_node
```
roslaunch terminal show information about each frame, which I considered correct usage.
rosbag terminal show information about bag file:
```bash
[ INFO] [1542808888.348539169]: Opening test.bag

Waiting 0.2 seconds after advertising topics... done.

Hit space to toggle paused, or 's' to step.
 [RUNNING]  Bag Time: 1526020923.272625   Duration: 22.771921 / 22.804345               88.05 
Done.
```
Another point is that, my catkin_ws is actually ```~/Workspace/Mapper/catkin_ws``` instead of default one. Does this affect the process at all?
______________________________________________________________________________________________________________
This is first time I used ROS/catkin, could you please provide any solution for this?
Thanks in advance!

**Comment by WANG-KX** [comment]
**col_depth** is the name of the published message. You can see the message by `rqt_image_view` in your terminal.
Please follow the [ROS tutorial](http://wiki.ros.org/ROS/Tutorials).
